In [1]:
import numpy as np
import cv2

In [4]:
# Read our logo using cv2.imread
img = cv2.imread("opencv-logo.png", 1)

In [5]:
# Image dimension, all pixels found in the image
img

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [6]:
type(img)

numpy.ndarray

In [8]:
len(img) # 739 Pixels

739

In [12]:
len(img[0]) # Shows that there are 600 vertical columns

600

In [14]:
len(img[0][0])   # 3 Channels (Number of channels found in this image)

3

In [16]:
img.shape  # Tells us the number of horizontal rows , columns and number of channels

(739, 600, 3)

In [18]:
img.dtype  # Can know the data type of the image (unsigned integer)

dtype('uint8')

In [19]:
# This tells us that the range of values varies from 0 = 255

2**8

256

In [22]:
# Can slice the image to get

img[10, 5]  # the tenth row and the fifth column 

# This outputs the pixel values of this array
# 255, 255, 255 for the RGB channels

array([255, 255, 255], dtype=uint8)

In [24]:
# If I want to see all of the single channel 

img[:, :, 0]

# this gives us a one channel that gives us all the pixels in the first channel

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [26]:
# To access the size parameter 

img.size

# This outputs the total number of pixels contained inside this image

1330200